(** * model.group_order: the order of [G] and the cofactor of the curve. *)
(** Copyright (C) 2026 remix7531
    SPDX-License-Identifier: MIT *)

(** The two arithmetic facts that turn [model.group]'s curve into THE secp256k1
    group: the generator has order exactly [secp256k1_N], and the curve has
    cofactor one, so every point on it is a multiple of [G].

    Together they are what lets a scalar be treated as an element of [Z/nZ]
    everywhere above this layer: BIP-340 verification compares [s*G] against
    [R + e*P] with [s] and [e] reduced mod [n], which is only meaningful once
    [smul] is known to factor through [Z/nZ] on curve points.

    STATUS.  Both are STATED AND [Admitted].

    INTENDED DISCHARGE ROUTE: coqprime's [Coqprime/elliptic] development, whose
    point-order machinery (a Pocklington-style certificate for the order of a
    point, over the same [F_p] instance [model.group_law] needs) is what proves
    a concrete generator has a concrete prime order; [cofactor_one] then follows
    from the Hasse bound plus [secp256k1_N > 2^256 - 2^129], since a group of
    order [n] inside an interval of width [2*sqrt(p)] admits no larger
    supergroup on this curve.  Both lines are in [audit/scaffold.txt].

    This file sits under [model/] rather than [theory/] because it mentions
    model definitions -- the same layering ruling that placed
    [model.jacobi_rules]. *)

Require Import ZArith.
Require Import Lia.
Require Import secp256k1.model.group.

Open Scope Z_scope.

(* ================================================================= *)
(** ** The order of the generator -- [G_order] (STATED, [Admitted]). *)

(** [G] has order exactly [secp256k1_N]: [n*G] is the identity, and no smaller
    positive multiple is.  The second conjunct is not decoration -- without it
    the first is satisfied by, say, the identity itself, and "the scalars are
    [Z/nZ]" would not follow.  [secp256k1_N] is prime ([model.constants]'s
    [secp256k1_N_prime], a coqprime certificate), so the two conjuncts together
    say the subgroup generated by [G] has prime order [n].
    Discharge route: coqprime [Coqprime/elliptic] (see the file header).
    See https://wuille.net/posts/secp256k1-tutorial/#231-the-secp256k1-generator *)
Lemma G_order :
  smul secp256k1_N G = PInf /\
  (forall k : Z, 0 < k < secp256k1_N -> smul k G <> PInf).
Proof.
  (* OUTSTANDING: awaits the Coqprime/elliptic port (see the file header). *)
Admitted.

(* ================================================================= *)
(** ** The cofactor is one -- [cofactor_one] (STATED, [Admitted]). *)

(** Every point of the curve is killed by [secp256k1_N]; equivalently, the
    curve group has order [n] and cofactor [1], so there is no small-subgroup
    structure to defend against and the C's
    [secp256k1_ge_is_in_correct_subgroup] ([src/group_impl.h:925-947]) is
    entitled to return [1] unconditionally outside exhaustive-test builds --
    which is exactly what its non-[EXHAUSTIVE_TEST_ORDER] branch does.  This is
    also the hypothesis-free half of [model.group_law]'s [lambda_endo]: the GLV
    identity needs the point to lie in [G]'s subgroup, and cofactor one makes
    "on the curve" enough.
    Discharge route: coqprime [Coqprime/elliptic] (see the file header).
    See https://wuille.net/posts/secp256k1-tutorial/#23-isomorphism-between-scalars-and-points *)
Lemma cofactor_one : forall a : Point, on_curve a -> smul secp256k1_N a = PInf.
Proof.
  (* OUTSTANDING: awaits the Coqprime/elliptic port (see the file header). *)
Admitted.
