(** * theory.primality.n: a Pocklington certificate for the secp256k1 group order. *)
(** Copyright (C) 2026 remix7531
    SPDX-License-Identifier: MIT *)

(** Proves [prime N] for the literal group order

      N = 115792089237316195423570985008687907852837564279074904382605163141518161494337

    the same digits as [model.constants.secp256k1_N] -- via a coqprime
    Pocklington certificate.  [Pocklington_refl] reduces primality of a
    number [p] to a boolean check once [p - 1] is fully factored and each
    distinct prime factor is itself already proved prime, so the proof is a
    chain of leaf [Lemma prime_<q> : prime q] built bottom-up, each closed by

      apply (Pocklington_refl (Pock_certif q a [(q1,e1);...] 1)
              ((Proof_certif q1 primeq1) :: ... :: nil)).
      vm_cast_no_check (refl_equal true).

    down to the primes small enough for coqprime's own base certificates
    ([prime2] / [prime3] / [prime149] / [prime631], re-exported by
    [PocklingtonRefl]).

    The factorisation chain for [N] itself:

      N - 1 = 2^6 * 3 * 149 * 631 * p1 * p2 * p3

      p1 = 107361793816595537             = 2^4 * 16699 * 85831 * 4681609
      p2 = 174723607534414371449          = 2^3 * 17 * 59 * 4051 * 120233 * 44706919
      p3 = 341948486974166000522343609283189
         = 2^2 * 3^3 * 109 * 29047611873442575647497758179

    and recursively for every composite [q - 1] above (16699, 85831,
    4681609, 120233, 44706919, 297159362677,
    29047611873442575647497758179, ...), bottoming out at the coqprime base
    primes.  The witness for [N] is [7]; every intermediate [prime_<q>]
    lemma carries its own witness, found by brute-force search over small
    bases.  The one non-recursive step is [162058447585428954701], a
    cofactor inside [p3 - 1]'s chain that trial division alone cannot
    crack; its two-factor split ([545358713 * 297159362677]) was found by
    Pollard's rho and is supplied as data rather than re-derived here.

    Generated by [gencert.py] (this directory): trial division plus
    Pollard's rho fully factors each [q - 1], then a small-base search picks
    each witness, and the result is emitted as the Rocq source below, leaves
    first.  Re-run it to regenerate this file from scratch should the
    literal [N] ever change.  This file itself compiles in about 1 second
    ([rocq compile -Q . secp256k1 theory/primality/n.v]).

    TRUST NOTE: [Print Assumptions secp256k1_N_prime_cert] lists Rocq's
    primitive 63-bit integer axioms ([Uint63Axioms.*] / [PrimInt63.*]),
    pulled in by coqprime's [BigN]-based certificate checker -- the same
    trust surface any coqprime user accepts.  No [Admitted], no project
    [Axiom] here: [model.constants.secp256k1_N_prime] is a [Qed] lemma
    ([exact secp256k1_N_prime_cert.]) over this certificate, so [Print
    Assumptions] on the headline closes over this file's [Uint63Axioms.*] /
    [PrimInt63.*] cone (whitelisted as foundational trust in
    [audit/AXIOM_WHITELIST]) instead of a project axiom. *)

From Coqprime Require Import PocklingtonRefl.
Local Open Scope positive_scope.

Lemma prime_5 : prime 5.
Proof.
 apply (Pocklington_refl (Pock_certif 5 2 ((2,2)::nil) 1)
        ((Proof_certif 2 prime2)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_11 : prime 11.
Proof.
 apply (Pocklington_refl (Pock_certif 11 2 ((2,1)::(5,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_23 : prime 23.
Proof.
 apply (Pocklington_refl (Pock_certif 23 5 ((2,1)::(11,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 11 prime_11)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_16699 : prime 16699.
Proof.
 apply (Pocklington_refl (Pock_certif 16699 3 ((2,1)::(3,1)::(11,2)::(23,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 11 prime_11)::(Proof_certif 23 prime_23)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_13 : prime 13.
Proof.
 apply (Pocklington_refl (Pock_certif 13 2 ((2,2)::(3,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_2861 : prime 2861.
Proof.
 apply (Pocklington_refl (Pock_certif 2861 2 ((2,2)::(5,1)::(11,1)::(13,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::(Proof_certif 11 prime_11)::(Proof_certif 13 prime_13)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_85831 : prime 85831.
Proof.
 apply (Pocklington_refl (Pock_certif 85831 3 ((2,1)::(3,1)::(5,1)::(2861,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 5 prime_5)::(Proof_certif 2861 prime_2861)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_97 : prime 97.
Proof.
 apply (Pocklington_refl (Pock_certif 97 5 ((2,5)::(3,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_67 : prime 67.
Proof.
 apply (Pocklington_refl (Pock_certif 67 2 ((2,1)::(3,1)::(11,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 11 prime_11)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_2011 : prime 2011.
Proof.
 apply (Pocklington_refl (Pock_certif 2011 3 ((2,1)::(3,1)::(5,1)::(67,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 5 prime_5)::(Proof_certif 67 prime_67)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_4681609 : prime 4681609.
Proof.
 apply (Pocklington_refl (Pock_certif 4681609 23 ((2,3)::(3,1)::(97,1)::(2011,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 97 prime_97)::(Proof_certif 2011 prime_2011)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_107361793816595537 : prime 107361793816595537.
Proof.
 apply (Pocklington_refl (Pock_certif 107361793816595537 3 ((2,4)::(16699,1)::(85831,1)::(4681609,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 16699 prime_16699)::(Proof_certif 85831 prime_85831)::(Proof_certif 4681609 prime_4681609)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_17 : prime 17.
Proof.
 apply (Pocklington_refl (Pock_certif 17 3 ((2,4)::nil) 1)
        ((Proof_certif 2 prime2)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_7 : prime 7.
Proof.
 apply (Pocklington_refl (Pock_certif 7 3 ((2,1)::(3,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_29 : prime 29.
Proof.
 apply (Pocklington_refl (Pock_certif 29 2 ((2,2)::(7,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 7 prime_7)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_59 : prime 59.
Proof.
 apply (Pocklington_refl (Pock_certif 59 2 ((2,1)::(29,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 29 prime_29)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_4051 : prime 4051.
Proof.
 apply (Pocklington_refl (Pock_certif 4051 10 ((2,1)::(3,4)::(5,2)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 5 prime_5)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_19 : prime 19.
Proof.
 apply (Pocklington_refl (Pock_certif 19 2 ((2,1)::(3,2)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_113 : prime 113.
Proof.
 apply (Pocklington_refl (Pock_certif 113 3 ((2,4)::(7,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 7 prime_7)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_120233 : prime 120233.
Proof.
 apply (Pocklington_refl (Pock_certif 120233 3 ((2,3)::(7,1)::(19,1)::(113,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 7 prime_7)::(Proof_certif 19 prime_19)::(Proof_certif 113 prime_113)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_199 : prime 199.
Proof.
 apply (Pocklington_refl (Pock_certif 199 3 ((2,1)::(3,2)::(11,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 11 prime_11)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_797 : prime 797.
Proof.
 apply (Pocklington_refl (Pock_certif 797 2 ((2,2)::(199,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 199 prime_199)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_41 : prime 41.
Proof.
 apply (Pocklington_refl (Pock_certif 41 6 ((2,3)::(5,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_9349 : prime 9349.
Proof.
 apply (Pocklington_refl (Pock_certif 9349 2 ((2,2)::(3,1)::(19,1)::(41,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 19 prime_19)::(Proof_certif 41 prime_41)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_44706919 : prime 44706919.
Proof.
 apply (Pocklington_refl (Pock_certif 44706919 6 ((2,1)::(3,1)::(797,1)::(9349,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 797 prime_797)::(Proof_certif 9349 prime_9349)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_174723607534414371449 : prime 174723607534414371449.
Proof.
 apply (Pocklington_refl (Pock_certif 174723607534414371449 3 ((2,3)::(17,1)::(59,1)::(4051,1)::(120233,1)::(44706919,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 17 prime_17)::(Proof_certif 59 prime_59)::(Proof_certif 4051 prime_4051)::(Proof_certif 120233 prime_120233)::(Proof_certif 44706919 prime_44706919)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_109 : prime 109.
Proof.
 apply (Pocklington_refl (Pock_certif 109 6 ((2,2)::(3,3)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_73 : prime 73.
Proof.
 apply (Pocklington_refl (Pock_certif 73 5 ((2,3)::(3,2)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_293 : prime 293.
Proof.
 apply (Pocklington_refl (Pock_certif 293 2 ((2,2)::(73,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 73 prime_73)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_2731 : prime 2731.
Proof.
 apply (Pocklington_refl (Pock_certif 2731 3 ((2,1)::(3,1)::(5,1)::(7,1)::(13,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 5 prime_5)::(Proof_certif 7 prime_7)::(Proof_certif 13 prime_13)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_305873 : prime 305873.
Proof.
 apply (Pocklington_refl (Pock_certif 305873 3 ((2,4)::(7,1)::(2731,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 7 prime_7)::(Proof_certif 2731 prime_2731)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_1409 : prime 1409.
Proof.
 apply (Pocklington_refl (Pock_certif 1409 3 ((2,7)::(11,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 11 prime_11)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_28181 : prime 28181.
Proof.
 apply (Pocklington_refl (Pock_certif 28181 2 ((2,2)::(5,1)::(1409,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::(Proof_certif 1409 prime_1409)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_545358713 : prime 545358713.
Proof.
 apply (Pocklington_refl (Pock_certif 545358713 5 ((2,3)::(41,1)::(59,1)::(28181,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 41 prime_41)::(Proof_certif 59 prime_59)::(Proof_certif 28181 prime_28181)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_461 : prime 461.
Proof.
 apply (Pocklington_refl (Pock_certif 461 2 ((2,2)::(5,1)::(23,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::(Proof_certif 23 prime_23)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_1871 : prime 1871.
Proof.
 apply (Pocklington_refl (Pock_certif 1871 14 ((2,1)::(5,1)::(11,1)::(17,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 5 prime_5)::(Proof_certif 11 prime_11)::(Proof_certif 17 prime_17)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_1627771 : prime 1627771.
Proof.
 apply (Pocklington_refl (Pock_certif 1627771 3 ((2,1)::(3,1)::(5,1)::(29,1)::(1871,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 5 prime_5)::(Proof_certif 29 prime_29)::(Proof_certif 1871 prime_1871)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_297159362677 : prime 297159362677.
Proof.
 apply (Pocklington_refl (Pock_certif 297159362677 2 ((2,2)::(3,2)::(11,1)::(461,1)::(1627771,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 11 prime_11)::(Proof_certif 461 prime_461)::(Proof_certif 1627771 prime_1627771)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_29047611873442575647497758179 : prime 29047611873442575647497758179.
Proof.
 apply (Pocklington_refl (Pock_certif 29047611873442575647497758179 2 ((2,1)::(293,1)::(305873,1)::(545358713,1)::(297159362677,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 293 prime_293)::(Proof_certif 305873 prime_305873)::(Proof_certif 545358713 prime_545358713)::(Proof_certif 297159362677 prime_297159362677)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma prime_341948486974166000522343609283189 : prime 341948486974166000522343609283189.
Proof.
 apply (Pocklington_refl (Pock_certif 341948486974166000522343609283189 2 ((2,2)::(3,3)::(109,1)::(29047611873442575647497758179,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 109 prime_109)::(Proof_certif 29047611873442575647497758179 prime_29047611873442575647497758179)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.

Lemma secp256k1_N_prime_cert : prime 115792089237316195423570985008687907852837564279074904382605163141518161494337.
Proof.
 apply (Pocklington_refl (Pock_certif 115792089237316195423570985008687907852837564279074904382605163141518161494337 7 ((2,6)::(3,1)::(149,1)::(631,1)::(107361793816595537,1)::(174723607534414371449,1)::(341948486974166000522343609283189,1)::nil) 1)
        ((Proof_certif 2 prime2)::(Proof_certif 3 prime3)::(Proof_certif 149 prime149)::(Proof_certif 631 prime631)::(Proof_certif 107361793816595537 prime_107361793816595537)::(Proof_certif 174723607534414371449 prime_174723607534414371449)::(Proof_certif 341948486974166000522343609283189 prime_341948486974166000522343609283189)::nil)).
 vm_cast_no_check (refl_equal true).
Qed.
